// Generated by scripts/process-helen-zeray-assets.mjs — do not edit by hand
import type { Artwork } from '../types/artwork'

export const artworks: Artwork[] = [
  {
    "id": "unnamed-feelings",
    "title": "unnamed feelings",
    "medium": "oil and acrylic on canvas",
    "dimensions": "100cm × 100cm",
    "year": "2026",
    "category": "painting",
    "available": false,
    "thumbnail": "/works/paintings/thumbs/unnamed-feelings.jpg",
    "full": "/works/paintings/full/unnamed-feelings.jpg",
    "colSpan": 1,
    "rowSpan": 1
  },
  {
    "id": "fantasies-impromptu",
    "title": "Fantasies impromptu",
    "medium": "oil and acrylic on canvas",
    "dimensions": "150cm × 130cm",
    "year": "2026",
    "category": "painting",
    "available": false,
    "thumbnail": "/works/paintings/thumbs/fantasies-impromptu.jpg",
    "full": "/works/paintings/full/fantasies-impromptu.jpg",
    "colSpan": 1,
    "rowSpan": 1
  },
  {
    "id": "nothing-but-honer",
    "title": "nothing but honer",
    "medium": "oil and acrylic on canvas",
    "dimensions": "120 cm × 130 cm",
    "year": "2025",
    "category": "painting",
    "available": false,
    "thumbnail": "/works/paintings/thumbs/nothing-but-honer.jpg",
    "full": "/works/paintings/full/nothing-but-honer.jpg",
    "colSpan": 1,
    "rowSpan": 1
  },
  {
    "id": "serenity",
    "title": "Serenity",
    "medium": "oil and acrylic on canvas",
    "dimensions": "130cm × 110cm",
    "year": "2025",
    "category": "painting",
    "available": false,
    "thumbnail": "/works/paintings/thumbs/serenity.jpg",
    "full": "/works/paintings/full/serenity.jpg",
    "colSpan": 1,
    "rowSpan": 1
  },
  {
    "id": "waited-for-no-one",
    "title": "waited for no one",
    "medium": "oil and acrylic on canvas",
    "dimensions": "130cm × 110cm",
    "year": "2025",
    "category": "painting",
    "available": false,
    "thumbnail": "/works/paintings/thumbs/waited-for-no-one.jpg",
    "full": "/works/paintings/full/waited-for-no-one.jpg",
    "colSpan": 1,
    "rowSpan": 1
  },
  {
    "id": "while-waithing",
    "title": "While waithing",
    "medium": "oil and acrylic on canvas",
    "dimensions": "150cm x 130cm",
    "year": "2025",
    "category": "painting",
    "available": false,
    "thumbnail": "/works/paintings/thumbs/while-waithing.jpg",
    "full": "/works/paintings/full/while-waithing.jpg",
    "colSpan": 1,
    "rowSpan": 1
  },
  {
    "id": "untitled",
    "title": "untitled",
    "medium": "mixed media",
    "dimensions": "130cm × 110cm",
    "year": "2025",
    "category": "painting",
    "available": false,
    "thumbnail": "/works/paintings/thumbs/untitled.jpg",
    "full": "/works/paintings/full/untitled.jpg",
    "colSpan": 1,
    "rowSpan": 1
  }
]

export const heroPaintingId = "serenity"
