// Generated by scripts/process-helen-zeray-assets.mjs
export const heroMarqueeImages = [
  {
    "src": "/works/paintings/thumbs/nothing-but-honer.jpg",
    "alt": "nothing but honer"
  },
  {
    "src": "/works/paintings/thumbs/serenity.jpg",
    "alt": "Serenity"
  },
  {
    "src": "/works/paintings/thumbs/fantasies-impromptu.jpg",
    "alt": "Fantasies impromptu"
  },
  {
    "src": "/works/paintings/thumbs/unnamed-feelings.jpg",
    "alt": "unnamed feelings"
  },
  {
    "src": "/works/paintings/thumbs/waited-for-no-one.jpg",
    "alt": "waited for no one"
  }
]
